# Generated by Django 3.0.7 on 2020-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='S', max_length=2, verbose_name=(('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'))),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='P', max_length=1, verbose_name=(('P', 'primary'), ('S', 'secondary'), ('D', 'danger'))),
            preserve_default=False,
        ),
    ]
