# Generated by Django 3.0.7 on 2020-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201016_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Details about said product goes here'),
            preserve_default=False,
        ),
    ]
